version: '3'

services:
  web:
    container_name: inventory_management-web-1
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq  
    networks:
      - default

  db:
    container_name: inventory_management-db-1
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=InventoryManagement
    ports: 
      - "5433:5432"
    restart: always
    networks:
      - default

  rabbitmq: 
    container_name: rabbitmq-container 
    image: rabbitmq:latest
    ports:
      - "5673:5672"  
      - "15673:15672"  
    networks:
      - default

networks:
  inventory_network:
    driver: bridge
